services:
  web:
    build:
      context: .
      dockerfile: Dockerfile # Укажите здесь свой Dockerfile, если имя отличается
    ports:
      - "733:4200" # Проброс порта 733 хоста на порт 4200 контейнера
    restart: always
