services:
  web:
    build:
      context: .
      dockerfile: Dockerfile # Укажите здесь свой Dockerfile, если имя отличается
    ports:
      - "733:733" # Проброс порта 733 хоста на порт 733 контейнера
    restart: always
    networks:
      - docker-network
networks:
  docker-network:
    external: true
